#!/bin/bash

mkdir -p build/golang

GOOS=windows GOARCH=amd64 go build -o build/golang/langforge-windows-amd64.exe
GOOS=windows GOARCH=arm64 go build -o build/golang/langforge-windows-arm64.exe

GOOS=darwin GOARCH=amd64 go build -o build/golang/langforge-macos-amd64
GOOS=darwin GOARCH=arm64 go build -o build/golang/langforge-macos-arm64

GOOS=linux GOARCH=amd64 go build -o build/golang/langforge-linux-amd64
GOOS=linux GOARCH=arm64 go build -o build/golang/langforge-linux-arm64

mkdir -p  pypi/langforge/bin

cp build/golang/* pypi/langforge/bin